INSERT INTO cliente(id,nome,email,tel,senha,sexo,datanasc)VALUES
(1,'Felipe Siqueira','lysgd@gmail.com','987654321','$2y$10$nbaF.iB1yhMmEyvDEFt4N.sonCkiQGttLbEpDYJ29eo16kBd.oG3e','masculino','2001-02-17'),
(2,'Uilson Castro','uilson@gmail.com','987654321','$2y$10$nbaF.iB1yhMmEyvDEFt4N.sonCkiQGttLbEpDYJ29eo16kBd.oG3e','masculino','2002-04-16'),
(3,'Matheus','matheus@gmail.com','987654321','$2y$10$nbaF.iB1yhMmEyvDEFt4N.sonCkiQGttLbEpDYJ29eo16kBd.oG3e','masculino','2001-12-21'),
(4,'Thaynan','thaynan@gmail.com','987654321','$2y$10$nbaF.iB1yhMmEyvDEFt4N.sonCkiQGttLbEpDYJ29eo16kBd.oG3e','masculino','2002-06-15'),



INSERT INTO receitas (idreceitas,nome,descricao,Modpreparo,ingredientes) VALUES 
('1','Bolo de banana','bolo feito de banana', 'mistura o bolo com as bananas',' bolo, banana'),
('2','Banana com açucar','Banana misturada com açucar', 'mistura o açucar com as bananas','banana, açucar'),
('3','Banana frita','deliciosa banana frita','frite a banana no oléo' ,'banana, açucar'),
('4','Banana ensopada','deliciosa banana ensopada','cozinhe a banana na água quente ' ,'banana, água'),
('5','Banana com sorvete','deliciosa banana com sorvete','coloque banana no sorvete' ,'banana, sorvete'),
('6', 'Coxinha', 'deliciosa coxinha','Esquenta tudo no microondas e pronto','Fermento, trigo, frango, sal'),
('7', 'Torresmo', 'Picante porco', 'Frita a o torresmo no oléo','Torresmo,carne de porco'),
('8','joelho',' Gostoso para caramba', 'Não utilize óleo, apenas o forno microondas será necessário','presunto,queijo,sal'),
('9', 'pastel', 'suculento', 'joga no oléo depois de juntar tudo', 'massa de pastel, queijo,carne, presunto'),
('10', 'Cigarreti', 'Enroladinho de salsicha', 'Não coma, pois é morte certa', 'massa de trigo, salsicha'),
('11','Doce de Banana','Doce feito com banana','  Corte as bananas em rodelas ecoloque numa panela com açúcar e deixe no fogo até dourar, sem desmanchar as bananas, reserve.Leve os ingredientes do creme ao fogo até engrossar (mexendo sempre).Despeje o creme em um pirex, coloque as bananas e por cima o suspiro de clara e leve ao forno até dourar.Deixe esfriar e leve à geladeira.','6 bananas nanicas maduras1 xícara de açúcar 1/2 litro de leite3 colheres de amido de milho2 gemas1 lata de leite 2 claras em neve com 4 colheres de açúcar Gotas de limão'),
('12','Frango Xadrez','Feito em 30 minutos','Tempere o frango com antecedência. Vc pode temperar como quiser, mas eu deixei uma sugestão dos ingredientes que uso. É importante não ser um tempero forte porque o molho que vai no final já é bem salgado.Refogue o frango no óleo até dourar. Junte a cebola e o alho e mexa por alguns segundos. Junte os pimentões e o brócolis. Acrescente 100ml de água e mantenha a panela tampada até os vegetais perderem o aspecto de cru. Eu gosto bem al dente, mas você pode deixar cozinhar até o ponto desejado. Junte o amendoim.','1 colher (sopa) rasa de colorar ou páprica picante;2 colheres (sopa) de shoyu;2 colheres (sopa) de água;1 colher (sopa) rasa de mostarda;1 colher (sopa) de suco de limão. 2 colheres (sopa) de óleo;500g de peito de frango em cubos;1/2 cebola picada em pedaços grandes;2 dentes de alho picados;1/3 de pimentão vermelho picado em pedaços grandes;1/3 de pimentão amarelo picado em pedaços grandes;1/3 de pimentão verde picado em pedaços grandes;1 xícara de brócolis ninja (miúdo) separado em buquês;50g de amendoim sem pele torrado;Cebolinha verde a gosto.'),
('13','Frango Assado na Cebola','Essa receita é muito fácil e prática','Comece temperando o frango. O tempero que eu usei é o meu “de sempre”. Deixe o frango marinando de um dia para o outro, mas se você não tiver tempo pode temperar com umas 2 horas de antecedência que dá certo.Eu usei 2 pedaços de coxa com sobrecoxa e para cada pedaço usei 1 cebola pequena picada em pétalas. Preaqueça o forno em 200º por 10 minutos .Retire o frango da marinada (reserve para usar depois) e passe para outro refratário untado com azeite (eu forro com alumínio para facilitar a limpeza, mas não precisa). Espalhe as pétalas de cebola em volta e uns pedacinhos de manteiga por cima. Cubra com papel alumínio e leve ao forno por cerca de 20 minutos.  Após 20 minutos o frango estará cozido, porém não muito dourado. Retire do forno, descarte o papel alumínio de cima e pincele um pouco da marinada que foi reservada. Leve novamente ao forno.A cada 10 minutos, retire do forno e espalhe um pouco mais da marinada sobre os pedaços de frango, repetindo essa operação até ficar bem dourado e crocante por cima. O tempo vai depender da potência do seu forno.Ele vai soltar bastante água e óleo. Ao final, eu retire esse óleo da assadeira (eu uso uma colher mesmo para isso) e volte ao forno por 3 minutos para “secar” bem.','Frango e Cebola'),
('14','Salada De Repolho Colorida','Bem Colorida','É só misturar! Pegue uma tigela, misture os repolhos, a cenoura e a maionese GOURMET.Se quiser, junte a uva-passa e mexa devagarinho.Coloque a salada numa travessa e guarde na geladeira até servir. Ela fica cremosíssima!','1 xícara (chá) de repolho branco picado fininho1 xícara (chá) de repolho roxo picado fininho1/2 xícara (chá) de cenoura ralada1 xícara (chá) de maionese Gourmet3 colheres de sopa de uva passa (opcional)'),
('15','Salada Verde com Molho Rosé','Salada com molho','Em uma tigela, coloque a maionese Hellmanns e o ketchup Hellmanns. Misture bem.Em uma saladeira, distribua a alface-frisée, a rúcula, o ovo, o rabanete e finalize com o tomate-cereja.Regue com o molho e sirva em seguida.','1/2 xícara de chá de Maionese Hellmanns3 colher de sopa de Ketchup Hellmanns Tradicionalfolhas de alface friséefolhas de rúcula2 ovos2 rabanetes em rodelas10 tomates cereja cortados ao meio'),
('16','Arroz com cenoura','Arroz nutritivo com cenoura','Lave e escorra o arroz. Em uma panela, refogue a cebola e aqueça o óleo. Junte o arroz, o sal e mexa bem até secar' ,'arroz, sal, cenoura, abobrinha, salsa, cebola'),
('17','Arroz com lentilha e cebola','Alternativa ao feijão, a lentilha é bastante versátil','Cozinhe a lentilha. Aqueça o óleo e refogue a cebola. Junte o caldo. Reduza o fogo.' ,'sal, óleo, cebola, arroz, legumes, manteiga'),
('18','Crepe de brigadeiro com calda de chocolate','Melhor que saborear um brigadeiro é saborear um crepe de brigadeiro','Bata todos os ingredientes da massa no liquidificador. Numa panela com fogo baixo, coloque todos os ingredientes. Derreta o chocolate. Coloque uma colher cheia do brigadeiro e jogue a calda por cima' ,'farinha de trigo, ovo, leite, chocolate, manteiga, noz'),
('19','Sopa de aveia','Uma sopa feita para momentos de clima frio','Derreta a margarina e refogue a cebola e o alho. Adicione água quente. Tampe a panela. Junte os flocos de aveia.' ,'margarina, cebola, alho, água, caldo de carne, flocos de aveia, tomate, queijo, sal, pimenta-do-reino’'),
('20','Escondidinho de batata doce com atum lata','Uma receita para aquelas ocasiões importantes','Faça o purê; Prepare o recheio:Lave as batatas, coloque-as numa panela coberta com água. Escorra e descasque as batatas. Por fim, monte o escondidinho: Forre o fundo de um recipiente com purê de batata' ,'batata doce, leite, margarina, atum, cebola, salsinha, azeitona verde, requeijão, queijo, sal, molho de pimenta')
